use alloy_primitives::Bytes as AlloyBytes;
use alloy_rpc_types_engine::PayloadAttributes as EthPayloadAttributes;
use alloy_rpc_types_eth::Withdrawal;
use reth::revm::primitives::{Address, B256, U256};
use reth_node_api::PayloadAttributes;
use serde_with::{Bytes, base64::Base64, serde_as};

use crate::db::model::StoredL1Origin;

/// Taiko Payload Attributes
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct TaikoPayloadAttributes {
    /// The ETH payload attributes
    #[cfg_attr(feature = "serde", serde(flatten))]
    pub payload_attributes: EthPayloadAttributes,
    /// Base fee per gas for the block.
    pub base_fee_per_gas: U256,
    /// The metadata for the Taiko block.
    pub block_metadata: TaikoBlockMetadata,
    /// The L1 origin information for the block.
    pub l1_origin: RpcL1Origin,
}

impl PayloadAttributes for TaikoPayloadAttributes {
    /// Returns the timestamp to be used in the payload job.
    fn timestamp(&self) -> u64 {
        self.payload_attributes.timestamp()
    }

    /// Returns the withdrawals for the given payload attributes.
    fn withdrawals(&self) -> Option<&Vec<Withdrawal>> {
        self.payload_attributes.withdrawals()
    }

    /// Return the parent beacon block root for the payload attributes.
    fn parent_beacon_block_root(&self) -> Option<B256> {
        self.payload_attributes.parent_beacon_block_root()
    }
}

/// The metadata for a Taiko block, which is generated by the Taiko protocol.
#[serde_as]
#[derive(Clone, Debug, Default, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct TaikoBlockMetadata {
    pub beneficiary: Address,
    pub gas_limit: u64,
    pub timestamp: U256,
    pub mix_hash: B256,
    pub tx_list: AlloyBytes,
    #[serde_as(as = "Base64")]
    pub extra_data: AlloyBytes,
}

/// The L1 origin information for a Taiko block, which includes the information about the L1 block
/// that including the given L2 block.
#[serde_as]
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct RpcL1Origin {
    #[serde(rename = "blockID")]
    pub block_id: U256,
    pub l2_block_hash: B256,
    pub l1_block_height: Option<U256>,
    pub l1_block_hash: Option<B256>,
    #[serde(rename = "buildPayloadArgsID")]
    pub build_payload_args_id: [u8; 8],
    pub is_forced_inclusion: bool,
    #[serde_as(as = "Bytes")]
    pub signature: [u8; 65],
}

impl RpcL1Origin {
    /// Checks if the L1 origin's L2 block is a preconfirmation block.
    pub fn is_preconf_block(&self) -> bool {
        self.l1_block_height.is_none() || self.l1_block_height == Some(U256::ZERO)
    }
}

impl From<StoredL1Origin> for RpcL1Origin {
    // Converts a `StoredL1Origin` into an `RpcL1Origin`.
    fn from(stored: StoredL1Origin) -> Self {
        RpcL1Origin {
            block_id: stored.block_id,
            l2_block_hash: stored.l2_block_hash,
            l1_block_height: (stored.l1_block_height != U256::ZERO)
                .then_some(stored.l1_block_height),
            l1_block_hash: (stored.l1_block_hash != B256::ZERO).then_some(stored.l1_block_hash),
            build_payload_args_id: stored.build_payload_args_id,
            is_forced_inclusion: stored.is_forced_inclusion,
            signature: stored.signature,
        }
    }
}
