[package]
name = "alethia-reth-bin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "alethia-reth"
path = "src/main.rs"

[dependencies]
alethia-reth-cli = { path = "../../crates/cli" }
alethia-reth-node = { path = "../../crates/node" }
reth = { workspace = true }
reth-cli-util = { workspace = true }
reth-rpc = { workspace = true }
tracing = { workspace = true }
